version: '3'
services:
  python:
    build: ./python_app
    command: flask run --host=0.0.0.0
    depends_on:
      - redis
    environment:
      - FLASK_APP=web.py
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "5000:5000"
    volumes:
      - ./python_app:/app
  redis:
    image: redis:3.0-alpine
